config/routes.rb
Rails.application.routes.draw do
  get 'topic/index'
  get 'topic/create'
  get '/topic/show/:id', to: 'topic#show', as: 'topic_show'
  get 'super_sub_categories/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :learnings do
    get 'more/:category_id', to: 'learnings#more', as: 'more'
  end
  resources :courses do
    resources :syllabus, only: [:index, :show, :create]
  end
   get '/generate_pdf', to: 'pdf#generate_pdf', as: 'generate_pdf'
  root 'learnings#index'
  resources :categories
  resources :subcategories
  # resources :syllabus
  # resources :syllabuses
  resources :banners
  resources :registration, only: [:new, :create, :index]
  resources :contacts
  resources :recommendations
  resources :instructors
  resources :faqs
  resources :courses
  resources :learnings
  get 'Advantage', to: 'learnings#Advantage',as: 'Advantage'
  get 'terms', to: 'learnings#terms', as: "terms"
  get 'privacy', to: 'learnings#privacy', as: "privacy"
  get 'refund', to: 'learnings#refund', as: "refund"
  get 'jobs', to: 'learnings#jobs', as: 'jobs'
  get 'procast', to: 'learnings#procast', as: 'procast'
  get 'login', to: 'learnings#login', as: 'login'
  get 'more', to: 'learnings#more', as: 'more'
  get 'pdf', to: 'learnings#pdf', as: 'pdf'
  get 'topic', to: 'learnings#topic', as: 'topic'
  # get '/topics/:id', to: 'topics#show', as: 'show_topic'

  resources :accounts, only: [:new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/forgot_password', to: 'password_resets#new', as: 'forgot_password'
  post '/forgot_password', to: 'password_resets#create'
  get '/password_reset/:token/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch '/password_reset/:token', to: 'password_resets#update'
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password

	attr_accessor :password_reset_token, :password_reset_sent_at

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

	def generate_password_reset_token
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.password_reset_sent_at = Time.zone.now
    save!
  end

	def password_reset_token_expired?
    password_reset_sent_at < 1.hours.ago
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
	has_one_attached :image
	has_many :subcategories
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
	has_one_attached :image
	has_many :syllabuses
end

app/models/faq.rb
class Faq < ApplicationRecord
	# belongs_to :learning
end

app/models/instructor.rb
class Instructor < ApplicationRecord
	has_one_attached :image
	# belongs_to :learning
end

app/models/learning.rb
class Learning < ApplicationRecord
	# has_many :courses
	# has_many :faqs
	# has_many :instructors
	# has_many :recommendations
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
	# belongs_to :learning
end

app/models/registration.rb
class Registration < ApplicationRecord
  validates :your_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_one_attached :image
  belongs_to :category
  has_many :super_sub_categories
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :course
  # scope :by_course, ->(course_id) { where(course_id: course_id) }
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :super_sub_category
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/learnings_controller.rb
class LearningsController < ApplicationController
   # before_action :set_user, only:[:show]
  def index
    @courses = Course.all
    @faqs = Faq.all
    @instructors = Instructor.all
    @recommendations = Recommendation.all
    @contacts = Contact.all
    @registrations = Registration.all
    @registration = Registration.new
    @banners = Banner.all
  end

  def more
    @categories = Category.all
    @subcategories = Subcategory.all
    @super_sub_categories = SuperSubCategory.all
    @registrations = Registration.all
    @registration = Registration.new
    @topics = Topic.all
  end

  def topic
    @super_sub_category = SuperSubCategory.find_by(params[:id])
    @topics = @super_sub_category.topics
    render 'learnings/topics'
  end

  def procast
    @blogs = Blog.all
  end

  def pdf
    # @registrations = Registration.all
    @registration = Registration.new
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/learnings/_header.html.erb
<style type="text/css">
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #80808017;
    }

    header {
        background-color: #ffd05a;
        color: black;
        padding: 10px 0;
    }
</style>
<body>
    <header>
        <div class="text-center">Next batch starting from 3rd February, 2024.<div class="text-center">Avail <span class="fw-7">60% off</span> now!</div></div>
    </header>
</body>

app/views/learnings/_navbar.html.erb
<style type="text/css">
@media (max-width: 992px) {
    .navbar-collapse {
        background-color: hsl(0deg 2.65% 6.9% / 78%);
        position: absolute;
        top: 60px;
        left: 0;
        right: 0;
    }

    .navbar-nav {
        width: 100%;
        text-align: center;
    }

    .navbar-nav .nav-item {
        display: block;
        margin-bottom: 10px;
    }

    .navbar-nav .nav-item:last-child {
        margin-bottom: 0;
    }

    .navbar-nav .nav-link {
        color: white !important;
    }

    .navbar-toggler {
        position: absolute;
        top: 0;
        right: 0;
    }
    .navbar-light .navbar-toggler-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 1)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
  }
} 
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-black" id="myHeader" style="z-index: 300; background-color: hsl(0deg 2.65% 6.9% / 78%)">
    <a href="/learnings">
        <svg width="50" height="50" viewBox="0 0 183 167" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M99.4946 0H27.4946H7.49463V20V53.2541C11.6309 44.3145 18.7127 37.0164 27.4946 32.6049V20H99.4946V20.0019C134.335 20.2706 162.495 48.5967 162.495 83.5C162.495 111.767 144.025 135.721 118.495 143.95V164.711C155.205 155.928 182.495 122.901 182.495 83.5C182.495 37.551 145.381 0.27047 99.4946 0.00146484V0ZM24.5585 138.362C17.6575 129.535 18.7509 117.002 26.771 109.485L14.4264 93.6955C-2.28188 108.047 -4.90408 133.149 8.80262 150.68C22.5093 168.212 47.5022 171.722 65.4615 158.97L53.1164 143.181C43.8862 149.151 31.4596 147.188 24.5585 138.362ZM69.4366 153.948L20.9536 91.9376L36.7081 79.6199L66.4456 117.655C68.5469 113.8 71.4535 110.301 75.1327 107.425C82.2837 101.834 91.0107 99.6424 99.3667 100.613L96.9367 120.465C93.6607 120.117 90.2517 120.991 87.4517 123.181C81.7327 127.651 80.7217 135.911 85.1927 141.63C88.2177 145.499 92.9787 147.213 97.5127 146.532L97.4997 166.623C87.0077 167.233 76.3997 162.854 69.4366 153.948ZM73.1725 51.1098C84.4465 65.5298 81.8965 86.3591 67.4765 97.6334L55.1578 81.8775C60.8761 77.4066 61.8874 69.1468 57.4166 63.4285C52.9457 57.7102 44.6859 56.699 38.9676 61.1698C33.2493 65.6406 32.238 73.9005 36.7089 79.6188L20.953 91.9375C9.67871 77.5175 12.2288 56.6881 26.6488 45.4139C41.0689 34.1396 61.8982 36.6897 73.1725 51.1098Z" fill="white"/>
        </svg>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <div class="container">
            <ul class="navbar-nav ml-auto">
                <%# if current_user %>
                    <li class="nav-item active">
                        <a class="nav-link" href="/learnings" style="color: white;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Courses" style="color: white;">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Instructors" style="color: white;">Instructors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#Request Callback" style="color: white;">Request Callback</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/procast" style="color: white;">Blogs</a>
                    </li>
                <%# else %>
                    <!-- <li class="nav-item">
                        <%= link_to 'Login | Signup', login_path, class: "nav-link" %>
                    </li> -->
                <%# end %>
            </ul>
        </div>
    </div>
</nav>
<script>
  window.onscroll = function() {myFunction()};

  var header = document.getElementById("myHeader");
  var sticky = header.offsetTop;

  function myFunction() {
    if (window.pageYOffset > sticky) {
      header.classList.add("sticky");
    } else {
      header.classList.remove("sticky");
    }
  }
  document.querySelectorAll('.navbar-nav .nav-link').forEach(function(navLink) {
    navLink.addEventListener('click', function() {
      smoothScrollToTop();
      setTimeout(function() {
        header.classList.remove("sticky");
      }, 1000);
    });
  });

  function smoothScrollToTop() {
    const currentScroll = document.documentElement.scrollTop || document.body.scrollTop;
    if (currentScroll > 0) {
      window.requestAnimationFrame(smoothScrollToTop);
      window.scrollTo(0, currentScroll - (currentScroll / 10));
    }
  }

</script>

app/views/learnings/login.html.erb
 <style type="text/css">
   @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
html,body{
  display: grid;
  height: 100%;
  width: 100%;
  place-items: center;
  background: -webkit-linear-gradient(left, #003366,#004080,#0059b3
, #0073e6);
}
::selection{
  background: #1a75ff;
  color: #fff;
}
.wrapper{
  overflow: hidden;
  max-width: 390px;
  background: #fff;
  padding: 30px;
  border-radius: 15px;
  box-shadow: 0px 15px 20px rgba(0,0,0,0.1);
}
.wrapper .title-text{
  display: flex;
  width: 200%;
}
.wrapper .title{
  width: 50%;
  font-size: 35px;
  font-weight: 600;
  text-align: center;
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
.wrapper .slide-controls{
  position: relative;
  display: flex;
  height: 50px;
  width: 100%;
  overflow: hidden;
  margin: 30px 0 10px 0;
  justify-content: space-between;
  border: 1px solid lightgrey;
  border-radius: 15px;
}
.slide-controls .slide{
  height: 100%;
  width: 100%;
  color: #fff;
  font-size: 18px;
  font-weight: 500;
  text-align: center;
  line-height: 48px;
  cursor: pointer;
  z-index: 1;
  transition: all 0.6s ease;
}
.slide-controls label.signup{
  color: #000;
}
.slide-controls .slider-tab{
  position: absolute;
  height: 100%;
  width: 50%;
  left: 0;
  z-index: 0;
  border-radius: 15px;
  background: -webkit-linear-gradient(left,#003366,#004080,#0059b3
, #0073e6);
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
input[type="radio"]{
  display: none;
}
#signup:checked ~ .slider-tab{
  left: 50%;
}
#signup:checked ~ label.signup{
  color: #fff;
  cursor: default;
  user-select: none;
}
#signup:checked ~ label.login{
  color: #000;
}
#login:checked ~ label.signup{
  color: #000;
}
#login:checked ~ label.login{
  cursor: default;
  user-select: none;
}
.wrapper .form-container{
  width: 100%;
  overflow: hidden;
}
.form-container .form-inner{
  display: flex;
  width: 200%;
}
.form-container .form-inner form{
  width: 50%;
  transition: all 0.6s cubic-bezier(0.68,-0.55,0.265,1.55);
}
.form-inner form .field{
  height: 50px;
  width: 100%;
  margin-top: 35px;
}
.form-inner form .field input{
  height: 100%;
  width: 100%;
  outline: none;
  padding-left: 15px;
  border-radius: 15px;
  border: 1px solid lightgrey;
  border-bottom-width: 2px;
  font-size: 17px;
  transition: all 0.3s ease;
}
.form-inner form .field input:focus{
  border-color: #1a75ff;
  /* box-shadow: inset 0 0 3px #fb6aae; */
}
.form-inner form .field input::placeholder{
  color: #999;
  transition: all 0.3s ease;
}
form .field input:focus::placeholder{
  color: #1a75ff;
}
.form-inner form .pass-link{
  margin-top: 45px;
}
.form-inner form .signup-link{
  text-align: center;
  margin-top: 30px;
}
.form-inner form .pass-link a,
.form-inner form .signup-link a{
  color: #1a75ff;
  text-decoration: none;
}
.form-inner form .pass-link a:hover,
.form-inner form .signup-link a:hover{
  text-decoration: underline;
}
form .btn{
  height: 50px;
  width: 100%;
  border-radius: 15px;
  position: relative;
  overflow: hidden;
}
form .btn .btn-layer{
  height: 100%;
  width: 300%;
  position: absolute;
  left: -100%;
  background: -webkit-linear-gradient(right,#003366,#004080,#0059b3
, #0073e6);
  border-radius: 15px;
  transition: all 0.4s ease;;
}
form .btn:hover .btn-layer{
  left: 0;
}
form .btn input[type="submit"]{
  height: 100%;
  width: 100%;
  z-index: 1;
  position: relative;
  background: none;
  border: none;
  color: #fff;
  padding-left: 0;
  border-radius: 15px;
  font-size: 20px;
  font-weight: 500;
  cursor: pointer;
}
</style>
<div class="wrapper">
  <div class="title-text">
    <div class="title login">Login</div>
    <div class="title signup">Signup</div>
  </div>
  <div class="form-container">
    <div class="slide-controls">
      <input type="radio" name="slide" id="login" checked>
      <input type="radio" name="slide" id="signup">
      <label for="login" class="slide login">Login</label>
      <label for="signup" class="slide signup">Signup</label>
      <div class="slider-tab"></div>
    </div>
    <div class="form-inner">
      <form action="<%= login_path %>" class="login" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <div class="field">
          <%= label_tag :email, "Email Address" %>
          <%= email_field_tag :email, nil, class: "form-control", required: true %>
        </div>

        <div class="field">
          <%= label_tag :password, "Password" %>
          <%= password_field_tag :password, nil, class: "form-control", required: true %>
        </div>

        <div class="pass-link">
          <%= link_to "Forgot password?", forgot_password_path %>
        </div>

        <div class="field btn">
          <div class="btn-layer"></div>
          <%= submit_tag "Login", class: "btn-submit" %>
        </div>

        <div class="signup-link">
          Not a member? <%= link_to "Signup now", accounts_path %>
        </div>
      </form>

      <%= form_with(model: @account, url: accounts_path, local: true) do |form| %>
        <div class="field">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control", placeholder: "Email Address", required: true %>
        </div>

        <div class="field">
          <%= form.label :password %>
          <%= form.password_field :password, class: "form-control", placeholder: "Password", required: true %>
        </div>

        <div class="field">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password", required: true %>
        </div>

        <div class="field btn">
          <div class="btn-layer"></div>
          <%= form.submit 'Signup', class: "btn-submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
   const loginText = document.querySelector(".title-text .login");
      const loginForm = document.querySelector("form.login");
      const loginBtn = document.querySelector("label.login");
      const signupBtn = document.querySelector("label.signup");
      const signupLink = document.querySelector("form .signup-link a");
      signupBtn.onclick = (()=>{
        loginForm.style.marginLeft = "-50%";
        loginText.style.marginLeft = "-50%";
      });
      loginBtn.onclick = (()=>{
        loginForm.style.marginLeft = "0%";
        loginText.style.marginLeft = "0%";
      });
      signupLink.onclick = (()=>{
        signupBtn.click();
        return false;
      });
</script>

app/views/learnings/terms.html.erb
<style type="text/css">
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #80808017;
    }
    .text-center{
        font-style: initial;
    }
    img{
        background-image: grey;
    }
    .container {
        display: flex;
        flex-direction: row-reverse;
    }
    .navbar-light .navbar-nav .nav-link {
        color: black;
        padding-right: 0.5rem;
        padding-left: 3.5rem;
        font-weight: bold;
    }
    button {
        background-color: blue;
        color: white; 
        padding: 10px 20px; 
        border: none;
        cursor: pointer;
        border: 2px solid white;
    }
    h1{
    	text-transform: capitalize;
    	margin-left: 78px;
    }

    @media (max-width: 992px) {
        .navbar-collapse {
            background-color: hsl(0deg 2.65% 6.9% / 78%);
            position: absolute;
            top: 60px;
            left: 0;
            right: 0;
        }

        .navbar-nav {
            width: 100%;
            text-align: center;
        }

        .navbar-nav .nav-item {
            display: block;
            margin-bottom: 10px;
        }

        .navbar-nav .nav-item:last-child {
            margin-bottom: 0;
        }

        .navbar-nav .nav-link {
            color: white !important;
        }

        .navbar-toggler {
            position: absolute;
            top: 0;
            right: 0;
        }
        .navbar-light .navbar-toggler-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 1)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
      }
    } 
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-black" id="myHeader" style="z-index: 300; background-color: hsl(0deg 2.65% 6.9% / 78%)">
    <a href="/learnings">
        <svg width="50" height="50" viewBox="0 0 183 167" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M99.4946 0H27.4946H7.49463V20V53.2541C11.6309 44.3145 18.7127 37.0164 27.4946 32.6049V20H99.4946V20.0019C134.335 20.2706 162.495 48.5967 162.495 83.5C162.495 111.767 144.025 135.721 118.495 143.95V164.711C155.205 155.928 182.495 122.901 182.495 83.5C182.495 37.551 145.381 0.27047 99.4946 0.00146484V0ZM24.5585 138.362C17.6575 129.535 18.7509 117.002 26.771 109.485L14.4264 93.6955C-2.28188 108.047 -4.90408 133.149 8.80262 150.68C22.5093 168.212 47.5022 171.722 65.4615 158.97L53.1164 143.181C43.8862 149.151 31.4596 147.188 24.5585 138.362ZM69.4366 153.948L20.9536 91.9376L36.7081 79.6199L66.4456 117.655C68.5469 113.8 71.4535 110.301 75.1327 107.425C82.2837 101.834 91.0107 99.6424 99.3667 100.613L96.9367 120.465C93.6607 120.117 90.2517 120.991 87.4517 123.181C81.7327 127.651 80.7217 135.911 85.1927 141.63C88.2177 145.499 92.9787 147.213 97.5127 146.532L97.4997 166.623C87.0077 167.233 76.3997 162.854 69.4366 153.948ZM73.1725 51.1098C84.4465 65.5298 81.8965 86.3591 67.4765 97.6334L55.1578 81.8775C60.8761 77.4066 61.8874 69.1468 57.4166 63.4285C52.9457 57.7102 44.6859 56.699 38.9676 61.1698C33.2493 65.6406 32.238 73.9005 36.7089 79.6188L20.953 91.9375C9.67871 77.5175 12.2288 56.6881 26.6488 45.4139C41.0689 34.1396 61.8982 36.6897 73.1725 51.1098Z" fill="white"/>
        </svg>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <div class="container">
            <ul class="navbar-nav ml-auto">
                <%# if current_user %>
                    <li class="nav-item active">
                        <a class="nav-link" href="/learnings" style="color: white;">Home</a>
                    </li>
<!--                     <li class="nav-item">
                        <a class="nav-link" href="/jobs" style="color: white;">Jobs</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="/procast" style="color: white;">Blogs</a>
                    </li>
                <%# else %>
                    <!-- <li class="nav-item">
                        <%= link_to 'Login | Signup', login_path, class: "nav-link" %>
                    </li> -->
                <%# end %>
            </ul>
        </div>
    </div>
</nav>
<br><br>
<h1>Terms and Conditions</h1>
<div class="container" style="display: flex; flex-direction: column;"><br>
    Welcome to Depth Core("we", "us", "our", "Depth Core") Please read these Terms and Conditions carefully before purchasing any courses from us. By purchasing courses from us, you agree to these Terms and Conditions.<br><br>
    <p><strong>1. Courses: </strong>We provide a range of courses designed to prepare students for software development engineer roles. Course details, including but not limited to content, duration, price, and instructor details, are available on our website.</p><br>
    <p><strong>2. Purchases: </strong>When you purchase a course from us, you agree to provide current, complete, and accurate purchase information. We reserve the right to refuse or cancel orders if fraudulent activity is suspected.</p><br>
    <p><strong>3. Refund Policy: </strong>All your purchases can be refunded within 7 days of registration.</p><br>
    <p><strong>4. Course Access: </strong>Upon successful purchase of a course, you will be granted access to course materials and live sessions. You agree to respect the intellectual property rights of the content provided and not to share access or content with any third parties.</p><br>
    <p><strong>5. Behavior and Conduct: </strong>We reserve the right to refuse service or access to the courses for any user who does not comply with the terms set out here, or who interferes with the ability of instructors to deliver courses or other students' ability to learn.</p><br>
    <p><strong>6. Changes to the Terms: </strong>We reserve the right, at our sole discretion, to modify or replace these Terms and Conditions at any time. It is your responsibility to periodically review these Terms and Conditions for updates.</p><br>
    <p><strong>7. Contact Us: </strong>If you have any questions about these Terms and Conditions, please contact us. Email id: arun@DepthCore.com Phone num: 9773728034</p><br>
</div>
<%= render "footer" %>

app/views/learnings/topics.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
        }
        .topic-list {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }
        .topic-item {
            margin-bottom: 10px;
        }
        .topic-link {
            color: #007bff;
            text-decoration: none;
        }
        .topic-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>

<div class="container">
    <h2>Topics </h2>
    <ul class="topic-list">
        <% @super_sub_category.topics.each do |topic| %>
            <li class="topic-item">
                <a href="<%= topic_show_path(topic) %>" style="color: orange;"><%= topic.title %></a>
            </li>
        <% end %>
    </ul>
</div>

</body>
</html>